#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1216_First_Floor -L "BMLG 1216 First Floor" -E -v lpd://10.200.3.246 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR -o printer-is-shared=false

else
lpadmin -p BMLG_1216_First_Floor -L "BMLG 1216 First Floor" -E -v lpd://10.200.3.246 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR.gz -o printer-is-shared=false

fi 

exit 0
