#!/bin/sh

# Install LabTech client for the 1214 building

/usr/sbin/installer -pkg /usr/local/bmlg_assets/labtech_1214_install/LTSvc.mpkg -target /

rm -rf /usr/local/bmlg_assets/labtech_1214_install

exit 0
