#!/bin/sh

# Install LabTech client for the 1219 building

/usr/sbin/installer -pkg /usr/local/bmlg_assets/labtech_1219_install/LTSvc.mpkg -target /

rm -rf /usr/local/bmlg_assets/labtech_1219_install

exit 0
