#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1221_Executive -L "BMLG 1221 Executive" -E -v lpd://10.200.3.129 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305 -o printer-is-shared=false

else
lpadmin -p BMLG_1221_Executive -L "BMLG 1221 Executive" -E -v lpd://10.200.3.129 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305.gz -o printer-is-shared=false

fi

exit 0
