#!/bin/sh

# Install LabTech client for the 1226 building

/usr/sbin/installer -pkg /usr/local/bmlg_assets/labtech_1226_install/LTSvc.mpkg -target /

rm -rf /usr/local/bmlg_assets/labtech_1226_install

exit 0
