#!/bin/sh

# Install LabTech client for the 1216 building

/usr/sbin/installer -pkg /usr/local/bmlg_assets/labtech_1216_install/LTSvc.mpkg -target /

rm -rf /usr/local/bmlg_assets/labtech_1216_install

exit 0
