#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1219_Second_Floor -L "BMLG 1219 Second Floor" -E -v lpd://10.200.3.247 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR -o printer-is-shared=false

else
lpadmin -p BMLG_1219_Second_Floor -L "BMLG 1219 Second Floor" -E -v lpd://10.200.3.247 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SR.gz -o printer-is-shared=false

fi

exit 0
