#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ C400DN"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ C400DN.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1221_Basement_Color -L "BMLG 1221 Basement Color" -E -v lpd://10.200.3.121 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ C400DN -o printer-is-shared=false

else
lpadmin -p BMLG_1221_Basement_Color -L "BMLG 1221 Basement Color" -E -v lpd://10.200.3.121 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ C400DN.gz -o printer-is-shared=false

fi

exit 0
