#!/bin/bash

# Create the Account

dscl . create /Users/user
dscl . create /Users/user UserShell /bin/bash
dscl . create /Users/user RealName "Fruit User"
dscl . create /Users/user UniqueID 501
dscl . create /Users/user PrimaryGroupID 20
dscl . create /Users/user NFSHomeDirectory /Local/Users/user
dscl . passwd /Users/user fruit
dscl . append /Groups/admin GroupMembership user

exit 0
