#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SF"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SF.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1221_Second_Floor_South -L "BMLG 1221 Second Floor South" -E -v lpd://10.200.3.135 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SF -o printer-is-shared=false

else
lpadmin -p BMLG_1221_Second_Floor_South -L "BMLG 1221 Second Floor South" -E -v lpd://10.200.3.135 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ SP\ 5210SF.gz -o printer-is-shared=false

fi

exit 0
