#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ 4001"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ 4001.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1221_First_Floor_North -L "BMLG 1221 First Floor North" -E -v lpd://10.200.3.145 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ 4001 -o printer-is-shared=false

else
lpadmin -p BMLG_1221_First_Floor_North -L "BMLG 1221 First Floor North" -E -v lpd://10.200.3.145 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ 4001.gz -o printer-is-shared=false

fi

exit 0
