#!/bin/bash

#Install the printer

driver="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305"
drivergz="/Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305.gz"

if [[ -e $driver ]]; then
lpadmin -p BMLG_1219_First_Floor -L "BMLG 1219 First Floor" -E -v lpd://10.200.3.176 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305 -o printer-is-shared=false -o Duplex=None

else
lpadmin -p BMLG_1219_First_Floor -L "BMLG 1219 First Floor" -E -v lpd://10.200.3.176 -P /Library/Printers/PPDs/Contents/Resources/RICOH\ Aficio\ MP\ C305.gz -o printer-is-shared=false -o Duplex=None

fi

exit 0
