#!/bin/sh

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki export PATH

# this will run as a munki install_check script
# exit status of 0 means install needs to run
# exit status not 0 means no installation necessary

# adapted scripts from  here: https://jamfnation.jamfsoftware.com/discussion.html?id=1989

# we need to check wether ARD is running

ardrunning=$(ps ax | grep -c -i "[Aa]rdagent")

if [[ $ardrunning -eq 0 ]]; then
	echo "ARD not running"
	exit 0
fi

echo "all is well"

exit 1
